### PR TITLE
Rename to circuits_spi

### PR DESCRIPTION
**Pull request by fhunleth**
This also adds back the NIF check so that its possible to build docs on OSX.

### CODE REVIEW

**Comment by mdsebald** [comment]
This is my oversight.  In README, SPI.open() replace "fd" with "ref",  and return value should be "{:ok, #Ref<…>}".  For SPI.transfer() replace "fd" with "ref".   

Also same question I had about NIF check code in GPIO PR.

**Comment by mdsebald** [comment]
Also, README makes a reference to Circuits.I2C,  should be Circuits.SPI

**Comment by fhunleth** [comment]
I dropped the NIF patch. I'll add that back in another PR and I think that I'd like to do it differently now that I've thought about it more.

**Comment by fhunleth** [comment]
Thanks for pointing out the other issues with the README. I'd like to address those in another PR, since this one is just for renaming the module name.

**Pull request merged**
